name: Bug Report
description: Something isn't working as expected.
labels:
  - 'type:bug :beetle:'
  - 'flag:triage :mailbox:'
body:
  - type: markdown
    attributes:
      value: Thank for taking the time to fill out this bug report!

  - type: dropdown
    id: mod
    attributes:
      label: What mod(s) is concerned by this issue?
      multiple: true
      options:
        - Keep My Keys
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: dropdown
    id: mc-version
    attributes:
      label: Minecraft version
      description: What version of Minecraft are you running?
      options:
        - 1.18.1 (Latest)
    validations:
      required: true

  - type: input
    id: mod-version
    attributes:
      label: Mod(s) version(s)
      description: |
        What version of the mods are you running?
        
        If multiple mods are affected, add all the mods versions
        with the mod name (saying "latest" is not valid).
      placeholder: ex. 1.0.0
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. If needed,
        please attach the full log file after submitting this form.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: |
        By submitting this issue, you agree to follow our
        [Code of Conduct]() (To be defined).
      options:
        # - label: I agree to follow this project's Code of Conduct
        #   required: true
        - label: I have searched the existing issues
          required: true
