name: labeler

on:
  issues:
    types: [opened, edited]

jobs:
  triage:
    runs-on: ubuntu-latest

    steps:
      - name: Label the issue
        uses: github/issue-labeler@v2.4.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          not-before: 2021-12-30T00:00:00Z
          enable-versioned-regex: 0
